firstcommit
xenonsequences/kolisnichenko-dmytro-IPZ-32 pull request #2
Opened 2023-10-19 20:19 UTC by xenonsequences

Закинув частину лаби

2023-10-20 10:42 UTC, xenonsequences commented
https://xenonsequences.github.io/kolisnichenko-dmytro-IPZ-32/

2023-10-21 09:07 UTC, vozniuk-lntu requested changes
1. тут еолір ссилки 000000 https://i.imgur.com/S7XdhWN.png
2. .link задай колір змінною
3. шрифт не той https://i.imgur.com/H6aF2j5.png
4. шрифт заголовку https://i.imgur.com/p4M0Ta5.png
5. стилі на портфоліо

2023-10-21 09:07 UTC, vozniuk-lntu commented on css/styles.css
> +    color: #2F303A;
inherit замість значення

2023-10-29 19:01 UTC, vozniuk-lntu approved these changes
1. можна не задавати для кожного класу кнопки шрифт а зробити для button щоб було успадкування
2. ти не виправив розмір шрифта https://i.imgur.com/1z3OveY.png
3. хіба там є він https://i.imgur.com/A236Q2s.png

це виправиш у наступній

2023-11-08 16:07 UTC, merged